/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NovelNovelIdRouteImport } from './routes/novel.$novelId'
import { Route as NovelNovelIdChapterChapterNumberRouteImport } from './routes/novel_.$novelId_.chapter_.$chapterNumber'

const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelNovelIdRoute = NovelNovelIdRouteImport.update({
  id: '/novel/$novelId',
  path: '/novel/$novelId',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelNovelIdChapterChapterNumberRoute =
  NovelNovelIdChapterChapterNumberRouteImport.update({
    id: '/novel_/$novelId_/chapter_/$chapterNumber',
    path: '/novel/$novelId/chapter/$chapterNumber',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/novel/$novelId': typeof NovelNovelIdRoute
  '/novel/$novelId/chapter/$chapterNumber': typeof NovelNovelIdChapterChapterNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/novel/$novelId': typeof NovelNovelIdRoute
  '/novel/$novelId/chapter/$chapterNumber': typeof NovelNovelIdChapterChapterNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/novel/$novelId': typeof NovelNovelIdRoute
  '/novel_/$novelId_/chapter_/$chapterNumber': typeof NovelNovelIdChapterChapterNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/downloads'
    | '/novel/$novelId'
    | '/novel/$novelId/chapter/$chapterNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/downloads'
    | '/novel/$novelId'
    | '/novel/$novelId/chapter/$chapterNumber'
  id:
    | '__root__'
    | '/'
    | '/downloads'
    | '/novel/$novelId'
    | '/novel_/$novelId_/chapter_/$chapterNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadsRoute: typeof DownloadsRoute
  NovelNovelIdRoute: typeof NovelNovelIdRoute
  NovelNovelIdChapterChapterNumberRoute: typeof NovelNovelIdChapterChapterNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novel/$novelId': {
      id: '/novel/$novelId'
      path: '/novel/$novelId'
      fullPath: '/novel/$novelId'
      preLoaderRoute: typeof NovelNovelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novel_/$novelId_/chapter_/$chapterNumber': {
      id: '/novel_/$novelId_/chapter_/$chapterNumber'
      path: '/novel/$novelId/chapter/$chapterNumber'
      fullPath: '/novel/$novelId/chapter/$chapterNumber'
      preLoaderRoute: typeof NovelNovelIdChapterChapterNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadsRoute: DownloadsRoute,
  NovelNovelIdRoute: NovelNovelIdRoute,
  NovelNovelIdChapterChapterNumberRoute: NovelNovelIdChapterChapterNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
