/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NovelNovelIdRouteImport } from './routes/novel.$novelId'

const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelNovelIdRoute = NovelNovelIdRouteImport.update({
  id: '/novel/$novelId',
  path: '/novel/$novelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/novel/$novelId': typeof NovelNovelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/novel/$novelId': typeof NovelNovelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/novel/$novelId': typeof NovelNovelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/downloads' | '/novel/$novelId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/downloads' | '/novel/$novelId'
  id: '__root__' | '/' | '/downloads' | '/novel/$novelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadsRoute: typeof DownloadsRoute
  NovelNovelIdRoute: typeof NovelNovelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novel/$novelId': {
      id: '/novel/$novelId'
      path: '/novel/$novelId'
      fullPath: '/novel/$novelId'
      preLoaderRoute: typeof NovelNovelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadsRoute: DownloadsRoute,
  NovelNovelIdRoute: NovelNovelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
